baseURL = "https://mrchazaaa.github.io/hugo-teletext-demo/"
languageCode = "en-gb"
title = "Charlie Howlett"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
# theme = "hugo-teletext"

[module]
  [[module.imports]]
    path = "github.com/mrchazaaa/hugo-teletext"

[params]
  enableScanlines = true

[[menus.footer]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.footer]]
  name = "Posts"
  pageRef = "/posts"
  weight = 20

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.highlight]
    noClasses = false
